### PR TITLE
[js-api] Throw RangeError when getArg's index is out of bounds

### LINKED ISSUE #184: Exceptions have a method `getArg` but parameters are the WASM signature's result types
Probably a nit but it seems like "arg" might be the wrong term. Perhaps it should be something more generic like `at`. `at` also has the upside of working nicely with anything that takes a list in the DOM.

Since it seems silly to make a new issue for something so small but perhaps we should throw a `RangeError` instead of a `TypeError` if the requested index out of bounds?

### PR DESCRIPTION
**Pull request by aheejin**
Closes #184.

### CODE REVIEW

**Review by Ms2ger — APPROVED** [review]
Sure. Do you want to update the "Getting out-of-range argument" subtest in `getArg.tentative.any.js` as well?

**Comment by aheejin** [comment]
@thibaudmichaud Is this change OK in the V8 implementation of JS API?

**Comment by thibaudmichaud** [comment]
Yes, this change should be straightforward.

**Review by thibaudmichaud — APPROVED** [review]

**Comment by aheejin** [comment]
@thibaudmichaud Has this been implemented? I ran this on https://github.com/web-platform-tests/wpt and it is failing:
```console
Running 3 tests in web-platform-tests

  ▶ Unexpected subtest result in /wasm/jsapi/exception/getArg.tentative.any.worker.html:
  │ FAIL [expected PASS] Getting out-of-range argument
  │   → assert_throws_js: function "() => exn.getArg(tag, value)" threw object "TypeError: WebAssembly.Exception.getArg(): Index must be convertible to a valid number" ("TypeError") expected instance of function "function RangeError() { [native code] }" ("RangeError")
  │ 
  │     at Test.<anonymous> (http://web-platform.test:8000/wasm/jsapi/exception/getArg.tentative.any.js:46:5)
  │     at Test.step (http://web-platform.test:8000/resources/testharness.js:2595:25)
  │     at test (http://web-platform.test:8000/resources/testharness.js:628:30)
  └     at http://web-platform.test:8000/wasm/jsapi/exception/getArg.tentative.any.js:26:1

  ▶ Unexpected subtest result in /wasm/jsapi/exception/getArg.tentative.any.html:
  │ FAIL [expected PASS] Getting out-of-range argument
  │   → assert_throws_js: function "() => exn.getArg(tag, value)" threw object "TypeError: WebAssembly.Exception.getArg(): Index must be convertible to a valid number" ("TypeError") expected instance of function "function RangeError() { [native code] }" ("RangeError")
  │ 
  │     at Test.<anonymous> (http://web-platform.test:8000/wasm/jsapi/exception/getArg.tentative.any.js:46:5)
  │     at Test.step (http://web-platform.test:8000/resources/testharness.js:2595:25)
  │     at test (http://web-platform.test:8000/resources/testharness.js:628:30)
  └     at http://web-platform.test:8000/wasm/jsapi/exception/getArg.tentative.any.js:26:1

Ran 3 tests finished in 8.8 seconds.
  • 1 ran as expected. 1 tests skipped.
  • 2 tests had unexpected subtest results
```

**Comment by thibaudmichaud** [comment]
It was implemented, but if the argument cannot be converted to a uint32, we throw a TypeError rather than a RangeError. This seems very similar to table.grow, which also throws a TypeError in this case: https://github.com/WebAssembly/spec/blob/main/test/js-api/table/grow.any.js. Wdyt about changing the getArg spec test for consistency?

I am not sure why we didn't catch that earlier though, we are supposed to include these tests in our test suite, I'll look into it.

**Comment by thibaudmichaud** [comment]
I didn't see that the test was only added to wpt a few hours ago, so that answers my last concern.

**Comment by Ms2ger** [comment]
Doh, my mistake in reviewing the test change. It seems like the "Index out of bounds" test above the changed one already expected the new behavior.

**Comment by Ms2ger** [comment]
#257

**Pull request merged**
