### PR TITLE
Merge reference types repo

### PR DESCRIPTION
**Pull request by aheejin**
This merges reference types repo. The only thing manually fixed was
resolving conflict in README.md.

cc @ioannad

### CODE REVIEW

**Comment by aheejin** [comment]
When merging, which button should I use, between "Create a merge commit" and "Rebase and merge"? (Certainly not "Squash and merge" this time :) ) "Create a merge commit" is currently disabled for this repo, but I can enable it if necessary.

**Comment by binji** [comment]
@aheejin You'll want "Create a merge commit". I typically merge manually from the command-line so I don't have to enable the option (since we normally don't want it).

**Comment by aheejin** [comment]
@binji Thanks!

By the way, this proposal also depends on multi-value. How should I maintain the merges between the two upstream repos? Just do merges from both repos and resolve conflicts?

**Comment by ioannad** [comment]
@aheejin I think the multi-value proposal is now merged in the main spec, so only the reference types spec needs to be merged here. What was the problem with #112 ?

**Comment by aheejin** [comment]
@ioannad I didn't mean there was a problem with #112, but you said there were lots of conflicts (because we didn't revert all squashed commits, I presume?), I thought it would be cleaner to revert all squashed commits (which I did in #115, #116, #117, and #119) and merge upstream from the fresh state.

**Comment by ioannad** [comment]
Oh I see, thank you for explaining! I had reverted #91 and #96 in #112 but I missed that #88 was also squashed. I'll remove #112 then, and I'll rebase my version of the current EH core spec, when this PR here is merged.

**Review by rossberg — APPROVED** [review]
Rubberstamp

**Comment by aheejin** [comment]
@Ms2ger Uh, sorry, you merged this using the command line..? This repo does not enable that option (unless you do that using the command line), so I'm wondering....

**Comment by Ms2ger** [comment]
Yeah, it would be a little silly to do all this work to create an actual merge commit and then squash it in the UI :)

**Pull request merged**
