### PR TITLE
Throw TypeError if new Exception or getArg would expose v128 to JS

### LINKED ISSUE #295: Missing s128 type check in the JS API?
If I am reading the spec correctly, s128 types are allowed in tags, whether the tag is defined in a wasm module, or created with the JS API's `WebAssembly.Tag` constructor.

But the `WebAssembly.Exception` constructor and the `WebAssembly.Exception#getArg` function use `ToWebAssemblyValue` and `ToJSValue` to convert values to/from JS, and this function simply asserts that the type is not `s128`. Is a type check missing here, or did I miss something?

### LINKED ISSUE #308: Unclear intended behavior for using WebAssembly.Exception.getArg to materialize a v128 member in JS
Per the current spec, when we call `WebAssembly.Exception.getArg`, we get a `payload` from `exn_read`, and invoke `ToJSValue` on an element of it.

From the definition of `exn_read`, the returned element we use for the payload is the field tuple from the exception instance, which is just some number of ordinary WebAssembly values `val*`.

But, in `ToJSValue`, we start off with this assertion:
> Assert: w is not of the form [v128.const](https://webassembly.github.io/exception-handling/core/exec/runtime.html#values) v128.

Since `v128` is an ordinary WebAssembly value type, it seems valid currently for one to occur in the return tuple of `exn_read`. But then, `getArg` funnels that value directly into `ToJSValue`, violating its invariants. I might be overlooking something? Otherwise, it seems like there should probably be a check for `v128` elements in `getArg` which throws a `TypeError`.

### PR DESCRIPTION
**Pull request by dschuff**
Fixes #308
Fixes #295

### CODE REVIEW

**Review by aheejin — APPROVED** [review]

**Comment by aheejin** [comment]
> Fixes #308 and #295

By the way in order to close both issues you need to prepend "fixes" to each of the issue, like, "fixes #xxx and fixes #yyy"

**Review by rossberg — COMMENTED** [review]
I believe there are more places that need to protect against exnref now, e.g., the Table constructor, Table#set, Table#grow, and perhaps others.

Overall, it would be simpler and more robust to move these checks into ToWebAssemblyValue, ToJSValue, and DefaultValue instead of duplicating them everywhere.

**Comment by dschuff** [comment]
OK yeah I'll look into that. I wasn't sure if there was some reason the checks weren't put into those places in the first place. Maybe we'll have change something to deal with the fact that they can throw now.

**Comment by dschuff** [comment]
Actually exnref is already handled in those places: IIRC you added them in your initial version that included the core spec. Since this change makes a symmetric change to Exception objects, I'm going to land it, but as i mentioned  in https://github.com/WebAssembly/exception-handling/issues/308#issuecomment-2164082932 and you mentioned here, maybe it does just make sense to sink those checks into ToJSValue/ToWebAssembly value etc.

**Comment by dschuff** [comment]
Regarding that change: it would be a refactoring that would affect both v128 and exnref and would be a no-op change compared to what's here. So, would it be better to do in the main spec repo after we merge this?

**Comment by rossberg** [comment]
> Actually exnref is already handled in those places

It definitely is missing in Table#grow. And in the Table constructor, but that presumably cannot encounter this case right now, since ToValueType cannot currently return exnref. However, it might in the future, so for the sake of robustness, it wouldn't harm to have a check there as well (which of course would be subsumed by the refactoring).

> So, would it be better to do in the main spec repo after we merge this?

Does that make it easier? I think it doesn't matter, and we could just as well do it while we're at it (and otherwise introduce more redundancy).

**Pull request merged**
